name: Report an issue with Aquarea Integration
description: Report an issue with Aquarea Integration.
title: "[Bug]: "
labels: ["bug", "requires-triage"]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here.
        
        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: home-assistant-version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core are you running?
      placeholder: 
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: input
    id: version  
    validations:
      required: true
    attributes:
      label: What version of the integration are you running?
  - type: textarea
    id: capabilities  
    validations:
      required: true
    attributes:
      label: Device description
      description: >-
        Capabilities of the heat pump:
        
        - Number of zones
        
        - Does it support cooling?
        
        - Does it have a DHW?

        - Any other detail that might be relevant
  - type: markdown
    attributes:
      value: |
        # Details
  - type: dropdown
    id: integration-loading
    validations:
      required: true
    attributes:
      label: Is the integration loading?
      options:
        - "Yes"
        - "No"
  - type: dropdown
    id: adapter-connected
    validations:
      required: true
    attributes:
      label: Is the adapter able to connect to the Aquarea Smart Cloud with a stable internet connection?
      options:
        - "Yes"
        - "No"
  - type: dropdown
    id: aquarea-web
    validations:
      required: true
    attributes:
      label: Are you able to perform the action you're trying to with the Aquarea Smart Cloud Site/App?
      options:
        - "Yes"
        - "No"
        - "N/A"
  - type: textarea
    attributes:
      label: Area of the issue
      description: >-
        Entities or features that you are experiencing the issue with. In case the integration is not loading, please specify the error your are seeing.

  - type: textarea
    attributes:
      label: Anything in the logs?
      description: For example, error message or stack traces. Please provide as much detail as possible.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
